name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcs-bq-loader

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gcs-bq-loader \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcs-bq-loader \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
