name: Deploy to Cloud Run Job

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write service account key to file
        run: echo '${{ secrets.GCP_SA_KEY }}' > "${{ github.workspace }}/key.json"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Activate service account
        run: gcloud auth activate-service-account --key-file="${{ github.workspace }}/key.json"

      - name: Configure Docker to authenticate with GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/trigger_contineously_gcs_to_bq

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs update gcs-bq-loader --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcs-bq-loader --region ${{ secrets.GCP_REGION }} || \
          gcloud run jobs create gcs-bq-loader --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcs-bq-loader --region ${{ secrets.GCP_REGION }}
